### ISSUE TITLE
Add this Helm chart into Azure/helm-charts?

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/helm-vsts-agent#1]
Any plan or constraint to integrate officially this VSTS Agent Helm chart into this Azure/helm-charts repository?
https://github.com/Azure/helm-charts/issues/127

**Comment by vglafirov** [comment]
@mathieu-benoit I think this repo is for Azure Service Catalog related charts only, as it described. This helm chart has nothing related to ASC, but I agree that have more generic Azure related repo is very useful. Let's see what Azure folks answer on your issue there.
And thanks for contribution.

**Comment by mathieu-benoit** [comment]
Oh I see, with OSBA... ok.
Yes having a more generic Azure Helm charts repo would be ideal. Here, with the vsts-agent chart, we are mandatory to clone the repo/pull the sources code to be able to deploy it. Having an associated chart repository would be more efficient/easier to deploy.

**Comment by vglafirov** [comment]
Closing this issue, since we won't be able to move it to Azure/helm-charts repo
