### ISSUE TITLE
Use new product naming (Azure DevOps / Azure Pipelines)

### ISSUE THREAD

**Issue by willsmythe** [Azure/helm-vsts-agent#10]
VSTS was rebranded as "Azure DevOps" in September 2018. The CI/CD features of Azure DevOps also now have their own name - "Azure Pipelines". 

The readme text, repo description, file names, etc in this repo (and optionally configuration property names) should be updated to reflect the new name.

Here are some pointers to how naming was changed in other repos to reflect the new branding:
* https://github.com/Microsoft/azure-pipelines-agent
* https://github.com/Microsoft/azure-pipelines-tasks

Also, "account" is now called "organization", so reflecting this in the configuration values, etc would be good as well. For example, instead of `vstsAccount`, use `azdevOrg` (or so it's really clear that the value needs to be the org's name versus its URL: `azdevOrgName`)

I am happy to help with this --- just let me know.

Will Smythe
(Program Manager for Azure DevOps / Azure Pipelines)

**Comment by vglafirov** [comment]
azure-pipelines-helm?

**Comment by mathieu-benoit** [comment]
Additional updates:

+ the Docker image is now here: `mcr.microsoft.com/azure-pipelines/vsts-agent`
+ the Docker Hub page should be updated based on Will description above: https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent

**Comment by brndkfr** [comment]
switching repo to read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) mode
