### ISSUE TITLE
Dead link for instructions

### ISSUE THREAD

**Issue by ST-DDT** [Azure/helm-vsts-agent#11]
> 1. Create a personal access token with the authorized scope **Agent Pools(read, manage)**  following these [instructions](https://docs.microsoft.com/en-us/vsts/git/_shared/personal-access-tokens). You will have to provide later the base64 encoded value of this token to the `vstsToken` value of the chart.

The `instructions` link is dead: `404 - Page not found`

In [README.md](https://github.com/Azure/helm-vsts-agent/blame/master/README.md#L38)

**Comment by brndkfr** [comment]
switching repo to read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) mode
