### ISSUE TITLE
Sharing Between Organisations

### ISSUE THREAD

**Issue by DinoSourcesRex** [Azure/helm-vsts-agent#12]
Hi.

I'm just wondering if it's possible to share VSTS agents between organisations?

I've got 2 organisations; Foo and Bar.

I generate the PAT token on Foo and set up the VSTS agents, that works fine - but is it possible to give Bar access too?

**Comment by brndkfr** [comment]
switching repo to read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) mode
