### ISSUE TITLE
Add chart to Helm Hub

### ISSUE THREAD

**Issue by NorDroN** [Azure/helm-vsts-agent#18]
Hi!
What about to add this chart to [Helm Hub](https://hub.helm.sh/charts)?
More info [here](https://github.com/helm/hub/blob/master/Repositories.md).

**Comment by brndkfr** [comment]
switching repo to read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) mode
