### ISSUE TITLE
Configure VSTS personal access token by pointing to a secret

### ISSUE THREAD

**Issue by mike-larson** [Azure/helm-vsts-agent#21]
In order to support a GitOps deployment pattern of this chart, you need to read the personal access token as a kubernetes secret from etcd, instead of requiring that the token is hardcoded directly in the values.yaml file.
Though I am aware sealed secrets would be an alternative option.

**Comment by brndkfr** [comment]
switching repo to read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) mode
