### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by dza89** [Azure/helm-vsts-agent#23]
Is there still anything happening on adp/ado/vsts agents on kubernetes?
There hasn't been any development for two years on this helm chart.
The current solution here is absolutely not feasible for a production environment:

-statefulset
-run as root or mounting the docker socket

Can someone at Microsoft create a proper way forward, because at the moment it seems that even at Microsoft nobody has any idea how to properly use a vsts agent on Kubernetes.

**Comment by gswallow** [comment]
I fought with this all morning and used https://hub.helm.sh/charts/emberstack/azure-pipelines-agent instead.  Came right up.

**Comment by dza89** [comment]
@gswallow 

Maybe I posted this in the wrong project.  I posted it here because this is the only MS agent project which is fully focused on kube.
Using a different helm chart does not solve running as a statefulset, mounting the docker socket and having to run as root.

The whole way of working of the agent is just really really, really bad on kubernetes. Really.

**Comment by keiransteele** [comment]
Definitely dead. I've been seeing a pattern of this happening. If they merged PRs it might not be such a problem but they also have control over the image. What is the point of open sourcing your project if you don't merge PRs?

The general concept of this is still valid though, what they have here works, you just need to maintain your own image (there image is out of date too) to mitigate the security issues.

**Comment by brndkfr** [comment]
switching repo to read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) mode
