### ISSUE TITLE
install fails with "Error: This command needs 1 argument: chart name"

### ISSUE THREAD

**Issue by kethahel99** [Azure/helm-vsts-agent#4]

**Comment by kethahel99** [comment]
I set the environment variable as advised in the readme.

PS C:\Users\*********\source\repos> helm install --name vsts --namespace vsts --set vstsToken=$vsts_token --set vstsAccount="********" --set vstsPool="*****" -f values.yaml vsts-agent .
Error: This command needs 1 argument: chart name

**Comment by m1pl** [comment]
Clone the repository and run this command in the checked out directory:
`helm install --name vsts --namespace vsts --set vstsToken=$vsts_token --set vstsAccount="" --set vstsPool="*****" -f values.yaml .`
You provided two arguments: `vsts-agent` and `.`, where you should only provide one argument, which in this case should be the directory containing the chart.

**Comment by vglafirov** [comment]
I believe this is fixed

**Comment by willmorgan** [comment]
@vglafirov The README still provides two arguments. Maybe that should be fixed?

https://github.com/Azure/helm-vsts-agent/blob/e047755f4ea90ef4ce9eeff90098cd8d45446efd/README.md#installing-the-chart

@mihaiplasoianu I'm running this command from the cloned directory but I still get the same error:

```
[willmorgan@mbp ~/Projects/helm-vsts-agent (master)]$ helm install --name vsts --set vstsToken=${VSTS_TOKEN} --set vstsAccount=${VSTS_ACCOUNT} --set vstsPool=${VSTS_POOL} -f values.yaml .
Error: This command needs 1 argument: chart name
```

This ticket should be reopened.

```
[willmorgan@mbp ~/Projects/helm-vsts-agent (master)]$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by willmorgan** [comment]
Resolved by doing this:

1. Cloning helm-vsts-agent to a directory `(~/Projects)`
2. From `~/Projects`, running `helm install helm-vsts-agent --set vstsToken=${VSTS_TOKEN} --set vstsAccount=${VSTS_ACCOUNT} --set vstsPool=${VSTS_POOL} -f helm-vsts-agent/values.yaml`

I'm not an expert on this, but the documentation definitely needs some love.
